---

- name: Setup Infrastructure in HCloud
  hosts: localhost
  become: no
  roles:
    - hetzner
  tags:
    - infrastructure
    - hetzner
    - hcloud

- name: Setup general system
  hosts: all
  become: yes
  roles:
    - system
  tags:
    - system
    - general