collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/hetzner.hcloud
    type: git
  - name: https://github.com/ansible-collections/kubernetes.core.git
    type: git