apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-storage
  namespace: longhorn-system
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"