---

- name: Block for all hosts
  tags:
      - kubernetes
      - kubernetes-all
      - kubernetes-setup
  block:
    - name: "Add cluster user"
      user:
        name: "cluster"
        groups:
          - "sudo"
        append: yes

    - name: Create deployment directory
      file:
        path: /var/deployment
        state: directory
        owner: cluster
        group: cluster

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - unattended-upgrades
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gpg
          - coreutils
          - git
          - htop
          - nano
          - nfs-common
          - unzip
          - python3-kubernetes
        state: present

    - name: Generate /etc/hosts file
      template:
        src: "{{ role_path }}/templates/hosts.j2"
        dest: /etc/hosts

    - name: Deploy private Key to server
      copy:
        src: "{{ role_path }}/files/id_ed25519"
        dest: /home/cluster/.ssh/id_ed25519
        mode: 0400
        owner: cluster
        group: cluster

    - name: Enable unattended upgrades
      apt:
        upgrade: dist
        update_cache: yes

    - name: Configure unattended-upgrades
      copy:
        content: |
          Unattended-Upgrade::Origins-Pattern {
            "o=Ubuntu,a=stable";
            "o=Ubuntu,a=stable-security";
            "o=Ubuntu,a=stable-updates";
          };
          Unattended-Upgrade::Automatic-Reboot "true";
        dest: /etc/apt/apt.conf.d/50unattended-upgrades