---

- name: Update apt package list
  apt:
    update_cache: yes

- name: Wait for the K3s server to be available
  command: >
    bash -c 'until curl -k https://master-nbg-0:6443; do sleep 5; done'
  register: curl_result
  until: curl_result.rc == 0
  retries: -1
  delay: 5

- name: Retrieve remote token
  shell: ssh -o StrictHostKeyChecking=accept-new cluster@master-nbg-0 sudo cat /var/lib/rancher/k3s/server/node-token
  register: remote_token
  become: true
  become_user: cluster

- name: Install K3s
  shell: curl -sfL https://get.k3s.io | K3S_URL=https://master-nbg-0:6443 K3S_TOKEN={{ remote_token.stdout }} sh -

- name: Ensure packages are updated and upgraded
  apt:
    upgrade: dist
    update_cache: yes

- name: Reboot if required
  reboot:
    msg: "Reboot initiated by Ansible for package updates"
    pre_reboot_delay: 60
    post_reboot_delay: 120
    reboot_timeout: 300

- name: Configure unattended-upgrades
  copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
        "o=Ubuntu,a=stable";
        "o=Ubuntu,a=stable-security";
        "o=Ubuntu,a=stable-updates";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades