---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  use-proxy-protocol: "false"
  default.conf: |
    server {
        listen 80;
        
        server_name _;

        location / {
                return 301 https://$host$request_uri;
        }
    }

    server {
        server_name kubernetes.jokester.cloud;

        location / {
          proxy_pass http://some-service.default.svc.cluster.local:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
    }