---

- name: Block for setting up the worker nodes
  tags:
    - kubernetes
    - kubernetes-worker
    - kubernetes-setup
    - worker
    - setup
  block:

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://master-nbg-0:6443 K3S_TOKEN="{{ k3s.token }}" sh -s - agent --node-name="$(hostname -f)" --node-ip={{ private_networks[0].ip }} --flannel-iface=enp7s0 --kubelet-arg="cloud-provider=external"
      async: 10
      poll: 0

    - name: create .kube directory
      file:
        path: /home/cluster/.kube
        state: directory
        owner: cluster
        group: cluster
    
    - name: Fetch hostkey of master-nbg-0
      shell: ssh-keyscan master-nbg-0
      register: host_key
      become_user: cluster

    - name: Add host keys to known_hosts
      lineinfile:
        path: /home/cluster/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      loop: "{{ host_key.stdout_lines }}"
      become_user: cluster

    - name: Copy kubeconfig from master
      shell: scp cluster@master-nbg-0:/etc/rancher/k3s/k3s.yaml /home/cluster/.kube/config
      become_user: cluster

    - name: Replace localhost with master-nbg-0 in kubeconfig
      replace:
        path: /home/cluster/.kube/config
        regexp: '127.0.0.1'
        replace: 'master-nbg-0'
      become_user: cluster