---

- name: Block for setting up backend-secrets
  tags:
    - kubernetes
    - kubernetes-secrets
    - secrets
    - kubernetes-pods
    - pods
  block:

    - name: Render secrets template
      template:
        src: "{{ role_path }}/templates/postgres-secrets.yaml.j2"
        dest: "/tmp/postgres-secrets.yaml"
        owner: root
        group: root
        mode: 0644

    - name: Apply secrets
      shell: kubectl apply -f "/tmp/postgres-secrets.yaml" --kubeconfig /etc/rancher/k3s/k3s.yaml